---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_COLLECTIONS_PATH: "~/.ansible/collections:~/collections"
verifier:
  name: ansible
