name: Hello World Role Molecule Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible ansible-lint yamllint docker 'molecule[docker]'
    - name: Molecule test
      run: |
        cd roles/hello_world
        molecule --debug test
